### ISSUE TITLE
No URL in config_jupyterhub_helm.yaml ?

### ISSUE THREAD

**Issue by julienchastang** [zonca/zonca.github.io-source#7]
https://github.com/zonca/zonca.github.io-source/blob/master/content/2017-12-05-scalable-jupyterhub-kubernetes-jetstream.md#install-jupyterhub

states 

"then download config_jupyterhub_helm.yaml from the repository and customize it with the URL of the master node (for Jetstream js-xxx-xxx.jetstream-cloud.org) and generate the random strings for security, finally run the Helm chart:"

Where is that URL customization supposed to happen? There is no URL attribute in that yaml file. Am I missing something?

**Comment by zonca** [comment]
sorry, now I splitted that in `secrets.yaml` that is created by https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/blob/master/create_secrets.sh

**Comment by zonca** [comment]
see also https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray-jupyterhub.html

I moved to install kubernetes with kubespray, see https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html
however even if you use kube-adm, you should be able to follow instructions from https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray-jupyterhub.html

**Comment by julienchastang** [comment]
OK thanks for update. I'll give the kubespray approach a try.
